window.gear=[
[1001, "Genin Kunai", "Stats", "ATK +20%", "None", "None"],
[1002, "Chunin Kunai", "Stats", "ATK +30%", "None", "None"],
[1091, "Genin Socks", "Stats", "SPD +20%", "None", "None"],
[1092, "Chunin Socks", "Stats", "SPD +30%", "None", "None"],
[1101, "Genin Headband", "Chakra", "Chakra Cost Reduced by 6%", "None", "None"],
[1102, "Chunin  Headband", "Chakra", "Chakra Cost Reduced by 9%", "None", "None"],
[1111, "Genin Glove Hooks", "Stats", "Crit Chance +10%", "None", "None"],
[1112, "Chunin Glove Hooks", "Stats", "Crit Chance +20%", "None", "None"],
[1081, "Genin Vest", "Stats", "DEF +20%", "None", "None"],
[1082, "Chunin Vest", "Stats", "DEF +30%", "None", "None"],
[1081, "Genin Jacket", "Stats", "HP +10%", "None", "None"],
[1082, "Chunin Jacket", "Stats", "HP +16%", "None", "None"],
[1122, "Genin Shuriken", "Skill", "Weapon Skill Damage +20%", "None", "None"],
[1123, "Chunin Shuriken", "Skill", "Weapon Skill Damage +30%", "None", "None"],
[1132, "Headband of Fortitude", "Stats", "DEF and HP +20%", "None", "None"],
[1142, "White Amulet", "Resistance", "Reduce the chance of Confusion", "None", "None"],
[1142, "Orange Amulet", "Resistance", "Reduce the chance of Sealed", "None", "None"],
[1152, "Bloodstained Katana", "Resistance", "Recover 2% HP when attacked", "None", "None"],
[1142, "Purple Amulet", "Resistance", "Reduce the chance of Poison", "None", "None"],
[1142, "Yellow Amulet", "Resistance", "Reduce the chance of Paralyzed", "None", "None"],
[1162, "Power Pills", "Stats", "For 3 turns, ATK +30%", "None", "None"],
[1012, "Scarlet Kunai", "Skill", "Fire Skill Damage +20%", "None", "None"],
[1022, "Amber Kunai", "Skill", "Taijutsu Skill Damage +20%", "None", "None"],
[1032, "Sky Blue Kunai", "Skill", "Unique Skill Damage +20%", "None", "None"],
[1072, "Snow White Kunai", "Skill", "Secret Skill Damage +20%", "None", "None"],
[1062, "Jet-Black Kunai", "Skill", "Summoning Skill Damage +20%", "None", "None"],
[1181, "Genin Smoke Ball", "Stats", "Dodge Rate +10%", "None", "None"],
[1182, "Chunin Smoke Ball", "Stats", "Dodge Rate +16%", "None", "None"],
[1162, "Pills of Herculean Strength", "Stats", "For 3 turns ATK +50%", "None", "None"],
[1162, "Pills of Patience", "Stats", "For 3 turns DEF +50%", "None", "None"],
[1163, "Pills of Endurance", "Stats", "For 3 turns DEF +100%", "None", "None"],
[1083, "Protection Vest - Lightning", "Resistance", "Reduce incoming Lightning Skill Damage", "None", "None"],
[1083, "Protection Vest - Water", "Resistance", "Reduce incoming Water Skill Damage", "None", "None"],
[1083, "Protection Vest - Wind", "Resistance", "Reduce incoming Wind Skill Damage", "None", "None"],
[1083, "Protection Vest - Earth", "Resistance", "Reduce incoming Earth Skill Damage", "None", "None"],
[1152, "Katana - Bright Yellow", "Skill", "Wood Skill Damage +20%", "None", "None"],
[1152, "Katana - Purple Electricity", "Skill", "Lightning Skill Damage +20%", "None", "None"],
[1133, "Focus Band", "Chakra", "Recover 5% Chakra after every action", "None", "None"],
[1082, "Jade Jacket", "Resistance", "Reduce the chance of getting Poisoned", "None", "None"],
[1082, "Immobility Jacket", "Resistance", "Reduce the chance of getting Paralyzed", "None", "None"],
[1082, "Crimson Jacket", "Resistance", "Reduce incoming Byakugan Skill Damage", "None", "None"],
[1083, "Adamantite Jacket", "Resistance", "Reduce incoming Taijutsu Skill Damage", "None", "None"],
[1002, "Jonin Kunai", "Stats", "ATK +40%", "None", "None"],
[1082, "Jonin Vest", "Stats", "DEF +40%", "None", "None"],
[1153, "Infallible Katana", "Additional", "Normal Attacks Can't Miss", "None", "None"],
[1203, "Makeout Paradise", "Skill", "Summoning Skill Damage +30%", "None", "None"],
[1213, "Gai's Tracksuit", "Resistance", "Reduced Damage from Taijutsu and Weapon Skill Damage, HP +10%", "None", "None"],
[1223, "Special Frog Suit", "Resistance", "Reduced Damage from Fire and Water Style Skill Damage, HP +10%", "None", "None"],
[1233, "Sword of Kusanagi", "Stats", "ATK +60%", "None", "None"],
[1083, "Protection Vest - Wood", "Resistance", "Reduce incoming Wood Skill Damage", "None", "None"],
[1093, "Gale Socks", "Stats", "SPD +50", "None", "None"],
[1243, "Awakening Pill", "Resistance", "Maximum HP +10%. For 2 turns, immune to negative effects", "None", "None"],
[1253, "Three Color Pills", "Stats", "For 3 turns, ATK and SPD +20%, DEF -20%", "None", "None"],
[1263, "Beach Umbrella", "Skill", "Wind Skill Damage increased +20%", "None", "None"],
[1273, "Luxury Sun Oil", "Resistance", "DEF +20%. For 2 turns, immune to Water Skill Damage.", "None", "None"],
[1284, "Missing Ninja Forehead Protector", "Chakra", "Maximum HP -20%, Chakra cost -12%", "None", "None"],
[1294, "Akatsuki Cloak", "Resistance", "Immune to bind status, Maximum HP +24%, SPD -20%", "None", "None"],
[1304, "Detoxification Injection", "Resistance", "ATK -10%. For 5 turns, immune to poison status", "None", "None"],
[1154, "Uchiha Blade", "Skill", "Sharingan Skill Damage +20%", "None", "None"],
[1053, "Rinnegan Kunai", "Skill", "Rinnegan Skill Damage +30%", "None", "None"],
[1073, "Byakugan Kunai", "Skill", "Byakugan Skill Damage +30%", "None", "None"],
[1043, "Water Kunai", "Skill", "Water Style Skill Damage +30%", "None", "None"],
[1003, "Magnetic Kunai", "Skill", "Magnetic Skill Damage +30%", "None", "None"],
[1003, "Medical Kunai", "Skill", "Medical Ninjutsu Skill Damage +30%", "None", "None"],
[1313, "Doctor's Ointment", "Skill", "Healing Amplified, SPD -20%", "None", "None"],
[1322, "Vitality Bandage", "Stats", "HP +2400", "None", "None"],
[1332, "Suntetsu of Fighting Spirit", "Stats", "ATK +5000", "None", "None"],
[1082, "Robust Jacket", "Stats", "DEF +5000", "None", "None"],
[1155, "Bloody Katana", "Additional", "Recover 5% HP when attacked", "None", "None"],
[1344, "Sai's Picture Book", "Resistance", "Greatly Reduce Chance of Getting Paralysed, HP -10%", "None", "None"],
[1354, "Customized Kunai", "Skill", "Space-Time Skill Damage +20%, SPD +30%", "None", "None"],
[1063, "Black Flames Kunai", "Skill", "Inferno Skill Damage +20%", "None", "None"],
[1364, "Three Blade Scythe", "Stats", "ATK +100%, HP -30%", "None", "None"],
[1374, "Haku's Mask", "Stats", "ATK +40%, SPD +40%, HP -40%", "None", "None"],
[1384, "Zabuza's Sword", "Stats", "ATK +40%, Water and Unique Skill Damage +20%", "None", "None"],
[1394, "Lightning Blade", "Stats", "ATK +40%, Lightning Style Damage +20%", "None", "None"],
[1404, "ANBU Mask", "Stats", "SPD +40%, Chakra cost -5%", "None", "None"],
[1414, "Hiruko", "Stats", "HP +4000, DEF +5000 and SPD -30%", "None", "None"],
[1424, "Zero", "Chakra", "After Each Action Recover 7% Chakra, Rinnegan Damage +7%", "None", "None"],
[1434, "Tsunade's Necklace", "Chakra", "Chakra cost reduced by 15%. At the end of each action low chance to restore 20% HP", "None", "None"],
[1444, "Long Sword - Samehada", "Stats", "ATK + 20%, Water Skill Damage +20%, Chance to recover 3000 HP after attack", "None", "None"],
[1445, "Recognition Bill", "Stats", "DEF, SPD and ATK +30%", "None", "None"],
[1464, "Goggles", "Skill", "Wind Style Skill Damage +20%, ATK +20%", "None", "None"],
[1474, "Taka Robe", "Stats", "Blaze Style Damage +40%, HP +40%", "None", "None"],
[1484, "Wind Shuriken", "Stats", "For 5 Turns ATK +150%", "None", "None"],
[1494, "Hiruzen's Helmet", "Additional", "When Damaged, Chance to Recover 5% Chakra", "None", "None"],
[1504, "Battle Bow", "Skill", "Secret Skill Damage +30%, ATK +10% (for 5 turns)", "None", "None"],
[1514, "Kazekage's Hat", "Skill", "Unique Skill Damage +30%, Max HP +20%", "None", "None"],
[1524, "Jiraiya's Forehead Protector", "Chakra", "Chakra Consumption decreased by 9%, Summoning Skill Damage +20%", "None", "None"],
[1535, "Ino's Chocolate", "Additional", "DEF +20%. After each action, Recover 3% Chakra", "None", "None"],
[1545, "Sakura's Chocolate", "Additional", "ATK +20%. After each action, HP +3%.", "None", "None"],
[1555, "Hinata's Chocolate", "Additional", "SPD +20%. After each action, HP +3%.", "None", "None"],
[1565, "Special Chocolate", "Additional", "After Each Turn Recover 5% HP and Chakra", "None", "None"],
[1574, "Large Sage Scroll", "Skill", "Maximum HP +30%, Sage Skill Damage +40%", "Maximum HP +40%, Sage Skill Damage +100%", "Naruto Uzumaki (Shippuden)"],
[1585, "Nine Tails' Chakra", "Chakra", "For 3 Turns Chakra Cost Reduced by 20%", "For 3 Turns Chakra Cost is 0", "Kurama Link Mode Naruto Uzumaki, Minato Namikaze"],
[1595, "Customized Kunai: Type 0", "Skill", "Space-Time Skill Damage +30%, SPD +40%", "Space Time Skill Damage +50%, SPD +40%, Immune to status", "Minato Namikaze"],
[1605, "Personal Frypan", "Stats", "ATK +80%", "ATK +80%. While HP is Above 70% ATK and DEF +100%", "Kushina Uzumaki"],
[1615, "Rose Bouquet", "Skill", "Sharingan Damage +30%", "Sharingan Damage +60%, After Each Action HP and Chakra +10%", "Itachi Uchiha"],
[1625, "Jet-Black Suit", "Resistance", "Incoming Sharingan Damage reduced, Sharingan Damage +10%", "Incoming Sharingan Damage Halved, Sharingan Damage +20%, Immune to Seal", "Itachi Uchiha (except ANBU Itachi)"],
[1635, "Moon-White Suit", "Resistance", "Incoming Secret Skill Damage reduced. Secret Damage +10%", "Incoming Secret Skill Damage Halved, Secret Damage +20%, Immune to Paralysis", "Deidara"],
[1645, "Blueish-Purple Suit", "Resistance", "Incoming Weapon Damage reduced, Weapon Damage +10%", "Incoming Weapon Damage Halved, Weapon Skill Damage +20%, Immune to Poison", "Sasori"],
[1655, "Sasuke's Waist Belt", "Resistance", "Incoming Sharingan Skill Damage are halved", "Immune to Sharingan Skill Damage, recover 10% HP and Chakra after every action", "Five Summit Sasuke Uchiha"],
[1665, "Sasuke's Chidori-Sword", "Stats", "ATK and Sharingan Skill Damage +30%", "ATK and Sharingan Skill Damage +100%", "Five Summit Sasuke Uchiha"],
[1675, "Temari's Fan", "Skill", "Wind Skill Damage +30%, SPD +10%", "All Skill Damage +70%, SPD +20%, Incoming Lightning Skill Damage halved", "Temari"],
[1685, "Mizukage's Hat", "Skill", "Water and Fire Style Damage +20%. Chance to be immune to debuffs", "All Skill Damage +70%, Immune to debuffs", "Mei Terumi"],
[1695, "Ring of Zero (Tendo)", "Chakra", "Gain 10% Chakra After Each Action, Rinnegan Skill Damage +10%", "Gain 10% Chakra and HP After Each Action, Rinnegan Skill Damage +50%", "Pain"],
[1705, "Makeout Tactics", "Skill", "Lightning Style & Sharingan Damage +20%, Max HP +20%", "Lightning Style & Sharingan Damage +50%, Max HP +40%", "Kakashi Hatake"],
[1715, "Sakura's Gloves", "Stats", "ATK and Taijutsu Skill Damage +30%", "ATK and Taijutsu Skill Damage +80%", "Sakura Haruno"],
[1725, "Poison Disabling Medicine", "Resistance", "Poison/Toxic effect duration halved", "Immune to Poison/Toxic. Chakra cost -10%. Medical ninjutsu HP recovery +60%.", "Sakura Haruno"],
[1745, "White Fang", "Stats", "ATK +40%, SPD +20%", "ATK +80%, SPD +40%", "Young Kakashi Hatake"],
[1765, "Obito's Goggles", "Additional", "Reduced damage from Sharingan Jutsu & HP +10%", "Receive half damage from Sharingan Jutsu, HP & DEF +40%", "Young Obito Uchiha"],
[1775, "Medical Pack", "Skill", "Effect of Recovery skills increased by 20%", "Effect of Recovery Skills +60%, HP and DEF increased by 5000", "Rin Nohara"],
[1755, "Team Minato's Backpack", "Resistance", "Reduced Damage from Fire, Wind and Lightning Stlye Jutsu, SPD -30%", "Half Damage from Fire, Wind and Lightning Stlye Jutsu", "Team Minato: Young Kakashi & Obito, Rin Nohara, and Jonin Minato"],
[1785, "Mazo Stakes", "Stats", "ATK and DEF +40%", "ATK and DEF +70%, Chakra Cost Reduced by 15%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
[1795, "Battle Mask", "Skill", "Fire Style and Sharingan Damage +20%", "HP +40%, Skill Damage +70%", "Adult Obito Uchiha (Non-Juubi Jinchuriki mode)"],
[1805, "Heaven Scroll", "Additional", "When damaged, chance to recover chakra +5%", "When damaged chance to recover chakra 100%, HP +50%, and Skill Damage +30%", "Pre-Shippuden Team 7: (Naruto, Sasuke, & Sakura) and Anko Mitarashi"],
[1815, "Earth Scroll", "Additional", "When damaged, chance to recover HP +5%", "When damaged chance to recover HP 100%, Chakra +50%, and Skill Damage +30%", "All Zaku, Dosu, & Kin Units, and Orochimaru (Except Sannin-era)"],
[1485, "Sasuke's Shuriken", "Stats", "ATK +60%, SPD +10%", "ATK +100%, SPD +30%, Fire Skill Damage +50%", "Pre-Shippuden Sasuke Uchiha"],
[1835, "Sage Horn", "Skill", "Sage Skill Damage and HP +10%", "Sage Skill Damage and HP +70%", "Sage Mode Kabuto Yakushi"],
[1845, "Kabuto's Glasses", "Resistance", "Genjutsu/Confusion status halved", "Immune to negative effects, Attack and Defense +70%", "Kabuto Yakushi"],
[1855, "Sasuke's Bow", "Skill", "Lightning Style Skill Damage and ATK +10%", "Lightning Style Skill Damage and ATK +60%", "Sasuke Uchiha"],
[1865, "Itachi's Crow", "Additional", "Regenerate 10% Chakra after an Action, Sharingan Damage +10%", "Regenerate 10% Chakra and HP after an Action, Sharingan Damage +60%", "Itachi Uchiha "],
[1875, "Waist Belt of the Sound Five", "Resistance", "Chance of falling under the sealed status is halved", "Immunity to Sealed and Confusion statuses. HP and DEF increased by 70%", "Sound Five (Jirobo, Tayuya, Sakon/Ukon, and Kidomaru, & Kimimaro Kaguya) Units"],
[1885, "Tayuya's Flute", "Skill", "ATK and SPD +20%, Genjutsu Skill Damage +20%", "ATK and SPD +50%, Genjutsu Skill Damage +100%", "Tayuya"],
[1895, "Kamatari's Lantern", "Additional", "Regenerate 5% Chakra after an Action, Wind Style Skill Damage +10%", "Regenerate 15% Chakra after an Action, All Jutsu's Damage +30%", "Temari"],
[1905, "Kunai and Paper Bomb", "Stats", "HP and ATK +40%", "HP and ATK +80%, Secret Skill Damage +60%", "Shikamaru Nara"],
[1915, "Madara's Fan", "Skill", "Fire Style and Rinnegan Skill Damage +20%", "All Skill Damage and ATK +60%", "Madara Uchiha"],
[1925, "Hashirama's Cells", "Additional", "Chance to grant immunity to skills, but -15% HP per turn", "+50% HP, greater chance of granting immunity to skills", "Madara Uchiha"],
[1935, "Junk Food", "Additional", "Max HP +15%", "None", "None"],
[1945, "Gamakichi Figurine", "Additional", "Reduced Damage from Fire, Sharingan and Lightning Style Jutsu", "Half Damage from Fire, Sharingan and Lightning Style Jutsu, Summoning Skill Damage+100%", "Naruto Uzumaki"],
[1955, "Manda Figurine", "Additional", "Reduced Damage from Taijutsu, SPD +20%", "TaiSkill Damage halved, SPD +40%, Summoning Skill Damage +80%", "Sasuke Uchiha"],
[1965, "Katsuyu Figurine", "Additional", "Reduced Damage from Wind and Sage Jutsu", "Reduced damage from all skills. Immune to debuffs.", "Sakura Haruno"],
[1975, "Pakkun Figurine", "Additional", "After Each Turn Recover 5% HP & Chakra", "After Each Turn Recover 10% HP and Chakra, Skill Damage +50%", "Kakashi Hatake"],
[1985, "Ino-Shika-Cho Piercing (Ino)", "Stats", "HP and SPD +20%", "HP & SPD +50%, Recovery skills increase recovery +50%", "Ino Yamanaka (Shippuden)"],
[1995, "Ino-Shika-Cho Piercing (Shika)", "Stats", "HP and DEF +20%", "HP & DEF + 50%, Weaknesses are disabled", "Shikamaru Nara (Shippuden)"],
[2005, "Ino-Shika-Cho Piercing (Cho)", "Stats", "HP and ATK +20%", "HP, ATK, and Secret Skill Damage +50%", "Choji Akimichi (Shippuden)"],
[2015, "Bingo Book", "Skill", "Wind Style Skill Damage +20%", "HP & ATK +30%, All Skill Skill Damage +80%", "Kakuzu"],
[2025, "Kakuzu's Ryo", "Additional", "Money gained from missions +20%", "Money gained from missions +20%, ATK & DEF +50%", "Kakuzu"],
[2035, "Summoning Scroll", "Skill", "Summoning Skill Damage +20%, HP & ATK + 20%", "Summoning Skill Damage +60%, HP & ATK + 40%", "Kakashi Hatake (Pre-Shippuden)"],
[1385, "Executioner's Blade", "Stats", "HP & ATK +20%, Unique skill Skill Damage +30%", "HP, ATK, & All Skill Skill Damage +50%", "Zabuza Momochi"],
[2045, "Senbon", "Stats", "ATK & SPD +20%. Water Skill Damage +30%", "ATK, SPD, and All skill Skill Damage +50%", "Haku"],
[1435, "Hokage Necklace", "Chakra", "Chakra consumption reduced by 10%. Recovery skills have a bonus 10% recovery", "Chakra Consumption reduced by 25%. All damaging and recovery skills have a 60% boost.", "Tsunade and Hashirama Senju"],
[1525, "Sannin: Jiraiya's Forehead Protector", "Chakra", "Chakra consumption reduced by 5%. Genjutsu and Summoning Skill Damage increased by 20%", "Chakra Consumption reduced by 20%. All Skill Damage increased by 80%.", "Jiraiya"],
[2055, "Deidara's Scope", "Skill", "Secret Skill Damage +20%, SPD +20%", "Secret Skill Damage +50%, SPD +50%", "Deidara"],
[2065, "Gaara's Sand Gourd", "Stats", "DEF +20%, Unique Skill Damage +20%", "ATK & DEF +50%, Unique Skill Damage +50%", "Gaara (Shippuden)"],
[2095, "Hashirama's Armor", "Stats", "Maximum HP & DEF +30%", "Maximum HP & DEF +50%. HP recovered by 15% after each action.", "Hashirama Senju"],
[2105, "Tobirama's Forehead Protector", "Chakra", "Chakra consumption decreased by 7%. Slight chance to dodge skills.", "Chakra consumption decreased by 20%. Chance to dodge skills.", "Tobirama Senju"],
[2115, "Hiruzen's Shuriken", "Stats", "ATK +80%", "ATK +120%. Skill Damage +30%", "Hiruzen Sarutobi"],
[2085, "Obito's Truth-Seeking Ball", "Additional", "All Skill Skill Damage +40%, Chakra recovery amount halved", "All skill Skill Damage +70%, great chance of skill avoidance", "Ten-Tails Obito Uchiha"],
[2075, "Obito's Staff", "Stats", "ATK & SPD +50%, HP reduced by 30% after every action", "ATK & DEF + 80%, SPD +40%", "Ten-Tails Obito Uchiha"],
[2145, "Anniversary Forehead Protector", "Chakra", "Chakra Consumption reduced by 5%", "Chakra consumption reduced by 15%. ATK and SPD +30%", "Sakura Haruno"],
[2125, "Anniversary Ladle", "Skill", "Unique Skill Damage +10%. Weakness damage received is reduced", "All Skill types +30% damage. Weakness damage received is halved", "Kushina Uzumaki"],
[2135, "Anniversary Pouch", "Stats", "HP +20%", "HP +30%, Skill Damage received is reduced", "Hinata Hyuga"],
[2155, "Anniversary Fan", "Stats", "SPD +30%", "ATK, DEF & SPD +30%", "Temari"],
[2165, "General Election Testimony", "Additional", "Chakra recovery +5%", "Chakra recovery +40%, Unique skill Skill Damage +20%", "Sakura Haruno, Kushina Uzumaki, Hinata Hyuga, Temari"],
[2205, "Crimson Ring", "Chakra", "Chakra restore +10% after each action, Sharingan Skill Damage +10%", "Chakra restore +20% after each action, All skill Skill Damage + 50%", "Itachi Uchiha (Except ANBU Itachi)"],
[2215, "Itachi's ANBU Mask", "Stats", "SPD +20%, Weapon Skill Damage +30%", "ATK & SPD +50%, all skill Skill Damage +100%", "Itachi Uchiha"],
[2225, "Throne", "Resistance", "Genjutsu Skill Damage received is halved, but HP is reduced 15% after each action", "Damage from Fire style, Sharingan and Genjutsu skill is halved, All skill Skill Damage +30%.", "Itachi Uchiha"],
[2175, "Ay's Belt", "Skill", "Taijutsu Skill Damage, ATK, & SPD +20%", "Taijutsu Skill Damage +70%, ATK & SPD + 30%", "Ay (Fourth Raikage)"],
[2185, "Bee's Pencil", "Skill", "Lightning Skill Damage & ATK + 30%", "All skill Skill Damage +70%. ATK +50%", "Killer Bee"],
[1445, "Samehada", "Skill", "Water style Skill Damage + 30%. HP +10%", "Water style Skill Damage +70%. HP & ATK +30%", "Kisame Hoshigaki"],
[2195, "South Ring", "Chakra", "Gain 10% Chakra after each action & Water style Skill Damage +10%.", "Gain 10% Chakra and HP after each action. Water style Skill Damage +60%", "Kisame Hoshigaki"],
[2235, "Sage Mode Coat", "Resistance", "Reduce duration of negative status & after each action -15% HP", "Halve duration of negative status & low chance to dodge skills", "Sage Mode Naruto Uzumaki"],
[2245, "Konohamaru's Scarf", "Stats", "ATK +70% & SPD +10%", "ATK +100%, SPD +20%, & all skill Skill Damage +50%", "Konohamaru Sarutobi"],
[2255, "Sun Necklace", "Stats", "ATK +100% & after each action HP -15%", "ATK & Skill Damage +100%, Jutsu casting speed increased by 1 step", "Pain"],
[2485, "White Bouquet", "Additional", "Recover Chakra by 5% after every action", "Byakugan Skill Damage +30%, recover Chakra by 20% after every action", "Hinata Hyuga"],
[2475, "Yellow Bouquet", "Additional", "Recover HP and Chakra by 3% after every action", "All Skill Damage +30%, recover 10% HP and Chakra after every action", "Mei Terumi"],
[2465, "Red Bouquet", "Additional", "Recover 5% HP after every action", "All Skill Damage +30%, recover 20% HP after every action", "Kushina Uzumaki"],
[2495, "Classy Sake Cups", "Additional", "Reduce the chance of falling into a negative state", "HP and QCK +50%, immune to negative status", "Kurenai Yuhi"],
[2265, "Gai's Nunchucks", "Stats", "ATK +80%, SPD +10%, but HP -30%", "ATK +100%, SPD +30%, HP +5000", "Might Gai"],
[2275, "Precious Stone", "Skill", "Max HP and Particle Style Skill Damage +30%", "HP +70%, all skill Skill Damage +120%", "Oonoki (Third Tsuchikage)"],
[2285, "Mu's Bandages", "Skill", "Particle Style Skill Damage +20%, Max HP and DEF +30%", "All skill Skill Damage +120%, HP & DEF +80%", "Mu (Second Tsuchikage)"],
[2295, "Mu's Bandana", "Chakra", "Chakra consumption reduced by 5%, ATK +20%", "Chakra consumption reduced by 10%, ATK & All Skill Skill Damage +50%", "Mu (Second Tsuchikage)"],
[2305, "Iwagakure Forehead Protector", "Chakra", "Chakra consumption reduced by 7%, recovery from healing skills +30%", "None", "None"],
[2315, "Iwagakure Sandals", "Stats", "SPD +30%, recovery from healing skills +20%", "None", "None"],
[2325, "Iwagakure Kunai", "Stats", "ATK +50%, DEF & HP +20%", "None", "None"],
[2505, "Jiraiya's Notepad", "Skill", "Fire Style and Summoning skill Skill Damage +20%", "All skill Skill Damage +70%, Max HP & SPD +30%", "Jiraiya"],
[2365, "Bee's White Scarf", "Stats", "ATK +70%, HP +10%", "ATK +100%, HP +20%. All skill types damage +50%", "Killer Bee"],
[2335, "Iruka's Letter", "Additional", "ATK, DEF & SPD +10%", "ATK, DEF & SPD +30%. Skill casting speed is up by 1 stage", "Kurama Link Mode Naruto Uzumaki"],
[2345, "Ay's Haori Jacket", "Resistance", "Incoming Lightning Style and Taijutsu Skill Damage is reduced, chakra consumption reduced by 5%", "Incoming Lightning Style and Taijutsu Skill Damage is halved, chakra consumption reduced by 15%", "Ay (Fourth Raikage)"],
[2355, "Ay's Right Arm Weight", "Stats", "ATK +70% & SPD +10%", "ATK +120% & SPD +20%. All skill types damage +30%", "Ay (Fourth Raikage)"],
[2555, "Kushina's Ladle", "Skill", "Unique Skill Damage and ATK +20%", "All Skill types damage & ATK +50%", "Kushina Uzumaki"],
[2515, "Flaky Jersey", "Resistance", "Reduced damage from Wind Style Jutsu", "Half damage from Wind and Unique Style Jutsu, Chance to dodge Skills", "Naruto Uzumaki (Pre-Shippuden) and Boruto Uzumaki"],
[2525, "Sarada's Glasses", "Resistance", "Chance of falling under the sealed status is halved", "Immunity to negative status, Skill Damage +40%", "Sarada Uchiha"],
[2545, "Seventh Hokage's Cloak", "Stats", "HP & DEF +30%", "HP & DEF +80%, SPD +40%", "Adult Naruto Uzumaki"],
[2535, "Sasuke's Cloak", "Stats", "HP & SPD +30%", "HP, SPD & Skill Damage +40%", "Adult Sasuke Uchiha"],
[2375, "Jugo's Cells", "Stats", "ATK & SPD +40%. HP reduced by 40% after every action", "Immune to paralysis, ATK & SPD +50%", "Sasuke Uchiha (Shippuden)"],
[2385, "Suigetsu's Water Bottle", "Additional", "HP restores by 10% after every action", "HP and Chakra restore by 20% after every action, Skill Damage +50%", "Suigetsu Hozuki"],
[2395, "Photo of Sasuke", "Additional", "DEF +20%, recover Chakra by 6% after every action", "DEF and recovery skill effect +50%, recover Chakra by 20% after every action", "Karin"],
[2405, "Bird", "Additional", "Rare chance to dodge skills", "Medium chance to dodge skills, recover HP and Chakra by 20% after every action", "Jugo"],
[2415, "Sasuke's White Jacket", "Stats", "Max HP & SPD +20%", "Max HP & ATK +100%, recover Chakra by 10% after every action", "Karin Sasuke Uchiha (Shippuden)"],
[2425, "Hebi's Cloak", "Resistance", "Incoming Fire, Water, Wind, Earth, and Lightning Style Skill Damage is reduced", "Incoming all skill Skill Damage is reduced, max HP & DEF +30%", "Taka: Sasuke Uchiha (Shippuden), Karin, Jugo, Suigetsu Hozuki"],
[2435, "Suigetsu's Head Cleaver", "Stats", "ATK and Weapon Skill Damage +40%", "ATK and all skill Skill Damage +80%, chance to dodge skills", "Suigetsu Hozuki"],
[2445, "Curtain", "Stats", "ATK +70% & Max HP +10%", "ATK +100%, Max HP +20%, all skill Skill Damage +50%", "Jugo"],
[2455, "Clay", "Additional", "ATK and Secret Skill Damage +30%", "ATK and Skill Damage +60%, skill casting speed is up by 1 stage", "Deidara"],
[2565, "Sasuke's Cursed Seal", "Stats", "Low chance to dodge skills, lose HP by 5% after every action", "High chance to dodge skills, max Chakra +100", "Sasuke Uchiha"],
[1235, "Orochimaru's Sword of Kusanagi", "Stats", "ATK +90%", "ATK +120%, all skill Skill Damage +70%", "Orochimaru (Except Sannin-era)"],
[2575, "Popsicle", "Stats", "ATK & DEF +15%", "None", "None"],
[2605, "Madara's Staff", "Stats", "ATK and Max HP +50%, lose Chakra by 20% after every action", "ATK and max HP +80%, SPD +40%", "Six Paths Madara Uchiha"],
[2665, "Dad's Kunai", "Stats", "ATK +60% & SPD +20%", "ATK +120%, SPD & all skill Skill Damage +30%", "Six Paths Naruto Uzumaki, Minato Namikaze"],
[2675, "Sword of Nunoboko", "Stats", "ATK +200%, reduction in max HP by 50%", "ATK +150%, max HP +50%", "Ten-Tails Obito Uchiha"],
[2685, "Obito's Memories", "Chakra", "Reduction in Chakra consumption by 20%, lose Chakra by 20% after every action", "Reduction in Chakra consumption by 30%, recover Chakra by 20% after every action", "Ten-Tails Obito Uchiha"],
[2695, "Obito's Imaginary Hat", "Skill", "All skill Skill Damage +40%, SPD -40%", "All skill Skill Damage +60%, DEF & SPD +40%", "Ten-Tails Obito Uchiha"],
[2705, "Transplanted Cells", "Chakra", "Recover chakra by 20% after every action, lose HP by 20% after every action", "Recover chakra by 20% after every action, reduction in Chakra consumption by 20%", "Sage Mode Kabuto Yakushi, Sasuke Uchiha"],
[2655, "Naruto's Palm Seal", "Additional", "Max Chakra increased by 5", "Full HP and Chakra recovery when HP reaches 0 (1 time only)", "Six Paths Naruto Uzumaki"],
[2645, "Naruto's Six Paths Coat", "Resistance", "Reduction in incoming damage from all skill types (except Six Paths), reduction in HP by 20% during every action", "Reduction in incoming damage from all skill types (except Six Paths), immunity to status effects", "Six Paths Naruto Uzumaki"],
[2625, "Naruto's Truth-Seeking Ball", "Skill", "All skill Skill Damage +40%, reduction in max HP by 50%", "Max HP and all skill Skill Damage +100%", "Six Paths Naruto Uzumaki"],
[2725, "Sasuke's Palm Seal", "Additional", "Max Chakra increased by 5", "Full HP and Chakra recovery when HP reaches 0 (1 time only)", "Six Paths Sasuke Uchiha"],
[2715, "Cursed Seal Sage Power", "Skill", "Sharingan and Rinnegan Skill Damage +30%", "All skill Skill Damage +100%, SPD +50%", "Six Paths Sasuke Uchiha"],
[2595, "Madara's Truth-Seeking Ball", "Skill", "Rinnegan skill Skill Damage +40%, SPD -30%", "All skill Skill Damage +80%, skill cast speed increased by 1 stage", "Six Paths Madara Uchiha"],
[2615, "Madara's Six Paths Coat", "Resistance", "Chance of received status effects and debuffs halved, reduction in DEF by 50%", "Immunity to status effects and debuffs, max HP & DEF +50%", "Six Paths Madara Uchiha"],
[2585, "Tailed Beast Chakra", "Chakra", "For 9 actions, Chakra consumption is reduced by 15%", "For 9 actions, Chakra consumption is halved and Skill Damage +50%", "Six Paths Naruto Uzumaki"],
[2735, "Gamble", "Stats", "Max HP & ATK +40%", "Max HP & ATK +80%, all skill Skill Damage +20%", "Tsunade"],
[2995, "Tsunade's Katsuyu Netsuke", "Additional", "Recovery skill effect +20%", "Recovery skill effect +70%, incoming Skill Damage is reduced", "Tsunade"],
[2775, "Straw Hat", "Chakra", "Reduction in Chakra consumption by 15%", "Reduction in Chakra consumption by 25%, max HP +50%", "Sakura Haruno"],
[2785, "Pink Jacket", "Resistance", "When HP is over 80%, chance of being inflicted with status effects is halved", "Immunity to status effects, max HP and defense +50%", "Hinata Hyuga"],
[2815, "Yellow Flower Hairpin", "Chakra", "Recover Chakra by 10% after every action", "Recover Chakra by 20% after every action, chance of HP recovery by 10% when attacked", "Ino Yamanaka"],
[2765, "Lifebuoy", "Stats", "ATK & DEF +30%", "ATK and DEF +80%, Skill Damage +20%", "Tenten"],
[2805, "Whistle", "Additional", "Max HP & ATK +30%", "Max HP & ATK +50%, Skill Damage +30%", "Iruka Umino"],
[2795, "Surfboard", "Stats", "ATK and SPD +30%", "ATK & SPD +50%, Lightning Style Skill Damage +20%", "Kakashi Hatake"],
[1265, "Beach Umbrella", "Skill", "Wind Style Skill Damage +40%", "All skill Skill Damage +70%, ATK & DEF +40%", "Temari"],
[1275, "Tsunade's Sun Oil", "Resistance", "DEF +30%, immunity to Water Style Skill Damage for up to 3 actions", "DEF +50%, immunity to Water Style Skill Damage. Medium chance to dodge skills", "Tsunade"],
[2825, "Hanzo's Defence Mask", "Chakra", "Recover 5% of Chakra at the end of every action. Fire Skill Damage +10%", "Recover 20% of Chakra at the end of every action. All Skill Damage +30%", "Hanzo of the Salamander"],
[2835, "Hanzo's Explosive Tags", "Skill", "Fire Skill Damage & ATK +20%", "Fire Skill Damage & ATK +70%. Skill Crit Chance +40%", "Hanzo of the Salamander"],
[2845, "Jiraiya's War Vest", "Additional", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Jiraiya"],
[2975, "Tsunade's War Vest", "Additional", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Tsunade"],
[2985, "Orochimaru's War Vest", "Additional", "All Skill Damage +10%", "All Skill Damage +50%. Skill Critical Strike Chance +30%", "Sannin-Era Orochimaru"],
[2855, "Jiraiya's Frog Suit", "Resistance", "Incoming Fire and Water Skill Damage are reduced. DEF -20%", "Incoming Skill Damage Reduced. ATK & DEF +40%", "Jiraiya"],
[2865, "Tsunade's Pouch", "Skill", "Healing Skills +20%. Maximum HP +20%", "Healing Skills +50%. Maximum HP & DEF +30%", "Tsunade"],
[2875, "Orochimaru's Mantle", "Resistance", "Reduced chance of being affected by abnormal states", "Abnormal State effects are halved. Maximum HP & SPD +30%", "Orochimaru"],
[3005, "Personal Tracksuit", "Resistance", "Incoming Taijutsu and Weapon Skill Damage is reduced, max HP +20%", "Incoming Taijutsu and Weapon Skill Damage is halved, chance to dodge skills, max HP +40%", "Might Gai and Rock Lee"],
[3015, "Lee's Weights", "Stats", "Max HP & ATK +60%, DEF -30%", "Max HP & ATK +100%, Skill Damage +30%", "Rock Lee"],
[3025, "Lee's Bandages", "Skill", "Taijutsu Skill Skill Damage +30%, SPD +20%", "Max HP & ATK +100%, Skill Damage +30%", "Rock Lee"],
[2885, "Kamatari's Scythe", "Stats", "ATK & SPD +30%", "HP & ATK +70%, SPD +40%", "Temari"],
[1095, "Sunagakure Socks", "Additional", "SPD +50. Restores 2% HP when hit", "SPD +80. Restores 10% HP when hit", "Temari, Gaara, and Kankuro (Shippuden)"],
[2954, "Giant Shuriken", "Stats", "ATK +100%, SPD +20%", "None", "None"],
[2894, "Amegakure Forehead Protector", "Chakra", "Chakra consumption is reduced by 10%, recover 10% of Chakra after every action", "None", "None"],
[2914, "Bamboo Pipe", "Skill", "All Skill Damage +30%, Water Style Skill Damage additional +50%", "None", "None"],
[3065, "Eight Trigrams Seal", "Additional", "Resistance to seal status", "Half resistance to debuffs and status effects, recover 10% of HP and Chakra after every action", "Naruto Uzumaki (Pre-Shippuden)"],
[3075, "Leaked Nine-Tails' Chakra", "Chakra", "Max Chakra +10, reduction in HP by 5% after every action", "Max Chakra +50, all Skill Damage +50%", "Naruto Uzumaki (Pre-Shippuden)"],
[2565, "Sasuke's Cursed Seal", "Additional", "Recover 7% of Chakra and lose 5% of HP after every action", "Recover 10% of Chakra after every action, Max Chakra +50", "Sasuke Uchiha (Pre-Shippuden)"],
[3035, "Sasuke's Forehead Protector", "Chakra", "Chakra consumption is reduced by 5%, ATK +20%", "Chakra consumption is reduced by 15%. Max HP, ATK & DEF +20%", "Sasuke Uchiha (Pre-Shippuden)"],
[3095, "Third Kazekage (Puppet)", "Skill", "Weapon and Magnet Style Skill Damage +40%, but HP is reduced by 10% after each turn", "All types Skill Damage +70%. Skill cast speed increased by 1 step", "Sasori"],
[3085, "Jewel Ring", "Chakra", "Chakra restore by 10% after each turn, Weapon Skill Damage +10%", "Chakra restore by 20% after each turn, all types Skill Damage +50%", "Sasori"],
[3135, "Naruto's Jersey", "Stats", "ATK and Wind Style Skill Damage +30%", "ATK and Wind Style Skill Damage +100%", "Naruto Uzumaki (Shippuden)"],
[3125, "Naruto's Forehead Protector", "Chakra", "Chakra consumption reduced by 5%, SPD +20%", "Chakra consumption reduced by 10%. Max HP, ATK & SPD +20%", "Naruto Uzumaki (Shippuden)"],
[3115, "Sasuke's Loincloth", "Resistance", "Reduced incoming damage from Wind Style type skills", "Halved incoming damage from Wind Style and Unique type skills. Skill Damage +30%", "Sasuke Uchiha (Shippuden)"],
[3105, "Sasuke's White Snake", "Additional", "Recover 10% of HP after every action. Lightning Style Skill Damage +10%", "Recover 10% of HP and Chakra after every action. Lightning Style Skill Damage +60%", "Sasuke Uchiha (Shippuden)"],
[3285, "Kakashi's Forehead Protector", "Chakra", "Chakra consumption reduced by 10%", "Chakra consumption reduced by 15%, recover 10% of HP every action", "Kakashi Hatake"],
[3305, "Kakashi's Undershirt", "Resistance", "Very low chance of skill immunity, max HP reduced by 50%", "Max HP +40%, medium chance of skill immunity", "Kakashi Hatake"],
[3295, "Makeout Violence", "Stats", "ATK +90%", "ATK +130%, all Skill Damage +30%", "Kakashi Hatake"],
[3395, "Naruto's Giant Scroll", "Skill", "ATK and Sage Art Skill Damage +40%", "For 3 actions, ATK and Sage Art Skill Damage +80%. For 3 turns after, ATK and Sage Art Skill Damage +150%", "Sage Mode Naruto Uzumaki"],
[3225, "Fukusaku Netsuke", "Additional", "Reduced incoming damage from Sharingan and Rinnegan type skills", "Halved incoming damage from Sharingan and Rinnegan type skills. Sage Skill Damage +60%", "Sage Mode Naruto Uzumaki"],
[3375, "Sage Art Chakra", "Chakra", "Recover 5% of Chakra after every action", "Recover 10% of Chakra after every action, max HP and Sage Art Skill Damage +50%", "Sage Mode Naruto Uzumaki, Jiraiya (except Sannin-era)"],
[3385, "Sword of Kusanagi - Chidori Blade", "Stats", "ATK +100%", "ATK +150%, skill cast speed increased by 1 step", "Sasuke Uchiha (Shippuden)"],
[3215, "Sasuke's Wristbands", "Resistance", "Reduced incoming damage from Wind Style and Sage Style type skills, SPD +10%", "Halved incoming damage from Wind Style and Sage Style type skills. ATK, DEF & SPD +50%", "Sasuke Uchiha (Shippuden)"],
[3205, "Sasuke's Hawk", "Additional", "Recover 10% of Chakra after every action, Sharingan Skill Damage +10%", "Recover 10% of HP and Chakra after every action. Sharingan Skill Damage +60%", "Sasuke Uchiha (Shippuden)"],
[3315, "Frog Gift", "Additional", "Max HP +30%, chance to recover 5% of HP when attacked", "Max HP +50%, recover 15% of HP when attacked", "Nagato, Konan, and Yahiko"],
[3325, "Nagato's Kunai", "Stats", "ATK +70%, DEF +30%", "ATK +100%. DEF and Skill Damage +40%", "Nagato"],
[3335, "Old Akatsuki Cloak", "Resistance", "Reduced incoming damage from Sharingan, Byakugan, and Rinnegan type skills", "Reduced incoming damage from all skill types except Wind Style, Sage Style, and Six Paths", "Nagato, Konan, and Yahiko"],
[3345, "Ino's Hairclips", "Skill", "Recovery skill effect +20%", "Recovery skill effect +50%, skill cast speed increased by 1 step", "Ino Yamanaka (Shippuden)"],
[3365, "Chouji's Chest Protecto", "Skill", "Secret Skill Damage +50%, SPD -20%", "All Skill Damage and DEF +70%, halved resistance to debuffs", "Choji Akimichi (Shippuden)"],
[3355, "Asuma's Chakra Blade", "Skill", "Secret and Weapon Skill Damage +30%", "All Skill Damage +70%, SPD +40%", "Shikamaru Nara (Shippuden) and Asuma Sarutobi"],
[3145, "Kabuto's Hood", "Additional", "All skill Skill Damage +10%", "All skill Skill Damage +30%, recover 10% of Chakra after every action", "Sage Mode Kabuto Yakushi"],
[3155, "Kabuto's Special Blood Transfusion Pack", "Stats", "Max HP and ATK +50%", "Max HP, ATK, DEF & SPD +80%", "Sage Mode Kabuto Yakushi"],
[3165, "Itachi's Cloak", "Resistance", "Incoming Sharingan damage halved", "Incoming Sharingan damage halved, DEF +100%", "Edo Tensei Itachi Uchiha"],
[3185, "Nagato's Cloak", "Resistance", "Incoming Rinnegan damage halved", "Incoming Rinnegan damage halved, DEF +100%", "Edo Tensei Nagato"],
[3175, "Shisui's Eye", "Additional", "Very low chance to dodge skills", "Chance to dodge skills, immunity to status effects", "Itachi Uchiha and Shisui Uchiha"],
[3195, "Asura Path Arm", "Skill", "Rinnegan Skill Damage +40%", "Rinnegan Skill Damage and ATK +80%", "Edo Tensei Nagato"],
[3965, "Obito's Chain", "Additional", "All Skill Damage +10%", "All Skill Damage +30%, critical rate +30% for skills with critical conditions", "Obito Uchiha Units (except Ten-Tails and Young)"],
[2915, "Utakata's Bubble Blower", "Stats", "ATK +70%, SPD +10%", "ATK +100%, SPD +20%, all Skill Damage +50%", "Utakata"],
[2905, "Nagato's Tube", "Skill", "Wind Style Skill Damage +30%, max HP +10%", "All Skill Damage +80%, max HP +40%", "Nagato (except Edo Tensei)"],
[2935, "Yahiko's Sword", "Stats", "ATK 100%", "ATK 150%, All Skill Damage +20%, Crit rate +20% for Skills that can Crit", "Yahiko"],
[3265, "Flaky Jersey", "Stats", "Max HP & DEF +50%", "Max HP & DEF +90%, skill cast speed increased by 1 step", "Naruto Uzumaki (Shippuden)"],
[3275, "Flaky Chainmail", "Resistance", "Low chance to dodge skills", "Low chance to dodge skills. When HP is over 50%, Dodge Rate rate is increased", "Naruto Uzumaki (Shippuden)"],
[3245, "Sasuke's Acquisition Seal", "Skill", "Weapon and Lightning Style Skill Damage +30%, SPD +10%", "Weapon and Lightning Style Skill Damage +120%, SPD +40%", "Sasuke Uchiha (Shippuden)"],
[3255, "Flaky Jacket", "Resistance", "Resistance to debuffs and status effects", "Halved resistance to debuffs and status effects. When HP is over 40%, halved incoming damage for all skill types", "Sasuke Uchiha (Shippuden)"],
[3045, "Valley of the End Statue (Left)", "Additional", "Recover 5% of Chakra and 3% of HP when attacked", "Recover 10% of Chakra and 5% of HP when attacked", "Madara Uchiha and Sasuke Uchiha"],
[3055, "Valley of the End Statue (Right)", "Additional", "Recover 5% of Chakra and 3% of HP when attacked", "Recover 10% of Chakra and 5% of HP when attacked", "Hashirama Senju and Naruto Uzumaki"],
[3434, "Shortcake", "Additional", "For 5 actions restore 20% HP", "None", "None"],
[3435, "Naruto's Shared Cake", "Additional", "For 5 actions restore 99% HP", "None", "None"],
[3415, "Fourth Hokage Cloak", "Resistance", "Quickness +20%, very low chance of skill dodge.", "Max HP, SPD & Skill Damage +50%. Medium chance of skill dodge.", " Fourth Hokage Minato Namikaze and Naruto Uzumaki (Chasing Your Dream)."],
[3405, "Shima's Home Cooking", "Additional", "For 3 actions, immunity to all Skill Damage. Max HP & SPD reduced by 30%.", "Critical rate & ATK +50%. For 3 actions, immunity to all Skill Damage.", "Sage Mode Naruto Uzumaki and Jiraiya"],
[3425, "Ancestor Statue", "Skill", "All Skill Damage +40%, but acquire weakness to all skills (excluding resistance and immunity)", "Max Chakra +20, Sage Art Skill Damage +120%", "Sage Mode Naruto Uzumaki and Jiraiya"],
[3465, "Hashirama's Giant Scroll", "Skill", "Max HP & Sage Art Skill Damage +30%", "Max HP & Sage Art Skill Damage +80%", "Hashirama Senju"],
[3445, "Hashirama's New Armor", "Stats", "ATK & DEF +50%", "ATK & DEF +50%, chance of full HP recovery after every action", "Hashirama Senju"],
[3485, "Tobirama's Ninja Sword", "Additional", "ATK +40%", "ATK +60%, all Skill Damage +60%", "Tobirama Senju"],
[3475, "Tobirama's Ninja Armor", "Stats", "ATK & SPD +50%", "ATK & SPD +50%, chance of SPD +100% after every action", "Tobirama Senju"],
[3515, "Rasa's Gold Dust", "Stats", "Max HP +50%", "Max HP & ATK +100%, recover 15% of HP after every action", "Rasa (Fourth Kazekage)"],
[3545, "Fourth Kazekage Hat", "Skill", "Magnetic Style Skill Damage +30%", "All Skill Damage +80%, recover 10% of Chakra after every action", "Rasa (Fourth Kazekage)"],
[3525, "Gaara's Tattoo", "Additional", "Resistance to status effects. Recover 5% of HP when attacked", "Halved resistance to status effects and debuffs. Recover 10% of HP when attacked", "Gaara"],
[1515, "Fifth Kazekage Hat", "Skill", "Unique and Sealing Skill Damage +40%", "All Skill Damage +80%, max HP +60%", "Gaara (Shippuden)"],
[3495, "Gengetsu's Gown", "Stats", "ATK & DEF +40%", "Max HP, ATK & DEF +100%", "Gengetsu Hozuki (Second Mizukage)"],
[3505, "Ohamaguri Netsuke", "Additional", "Very low chance to dodge skills", "Dodge rate +50%, medium chance to dodge skills", "Gengetsu Hozuki (Second Mizukage)"],
[1685, "Second Mizukage Hat", "Skill", "Water Style Skill Damage +30%", "All Skill Damage +80%, recover 10% of HP after every action", "Gengetsu Hozuki (Second Mizukage)"],
[3535, "Temari's Vest", "Resistance", "Incoming Fire, Water, and Wind Style Skill Damage reduced", "Incoming Fire, Water, and Wind Style Skill Damage halved. Medium chance to dodge skills", "Temari (Shippuden)"],
[3655, "Hiramekarei", "Skill", "Weapon Skill Damage +30%, ATK +10%", "ATK and Skill Damage +70%, max Chakra +50", "Chojuro"],
[3645, "Choujuro's Glasses", "Resistance", "Half resistance to Genjutsu and debuffs", "Immunity to Genjutsu and debuffs, max HP & ATK +50%", "Chojuro"],
[3605, "Kimimaro's Hair Ornaments", "Chakra", "Recover 5% of Chakra after every action", "Recover 10% of Chakra after every action. Chakra cost reduced by 10%", "Kimimaro Kaguya"],
[3595, "Kimimaro's Spine", "Stats", "ATK +150%, lose 30% of HP after every action", "ATK +150%, max HP +50%", "Kimimaro Kaguya"],
[3455, "Hashirama's Giant Blade", "Additional", "ATK +40%", "ATK +40%, additional 10 hits for skills with random damage", "Hashirama Senju"],
[3685, "Naruto's Racquet", "Skill", "Unique Skill Damage +30%", "ATK & Unique Skill Damage +60%. Immunity to seal status", "Naruto Uzumaki"],
[3695, "Sasuke's Racquet", "Skill", "Fire Style Skill Damage +30%", "ATK & Fire Skill Damage +60%. Immunity to paralysis status", "Sasuke Uchiha"],
[3705, "Sakura's Fan", "Skill", "Taijutsu and Unique Skill Damage +30%", "Taijutsu and Unique type skil damage +80%. Recovery effect +50%", "Sakura Haruno"],
[3715, "Hinata's Bath Set", "Skill", "Byakugan Skill Damage +30%", "Byakugan Skill Damage +80%, ATK & DEF +30%", "Hinata Hyuga"],
[3675, "Jiraiya's Scroll", "Skill", "ATK & Sage Art Skill Damage +20%", "Halved Chakra cost For 5 actions. After the 5th action and beyond, ATK & Sage Art Skill Damage +150%", "Jiraiya (Except Sannin-era)"],
[3665, "Stone Sword of the Frog Elegy", "Stats", "ATK & SPD +40%", "Max HP, ATK & SPD +50%. Skill Damage +30%", "Jiraiya (Except Sannin-era)"],
[3635, "Konan's Explosive Tag", "Stats", "Max HP & ATK +30%", "Max HP & ATK +100%. Skill Damage +30%", "Konan"],
[3625, "Konan's Head Ornament", "Chakra", "Max Chakra +5", "Max Chakra +50. Recover 10% of HP after every action", "Konan"],
[3615, "Konan's Origami", "Skill", "Unique Skill Damage +50%. Acquire weakness to Fire Style, Sharingan, and Sage Art type skills", "Skill Damage +80%. Max HP & SPD +30%", "Konan"],
[3725, "Pity on the Trash", "Stats", "ATK +80%", "Maximum HP +30% and ATK +100%, chance to dodge Skills", "Deidara"],
[3735, "Deidara's Forehead Protector", "Chakra", "For 3 turns, Chakra Cost -25%", "For 5 turns, Chakra Cost is halved and Skill Damage +100%", "Deidara"],
[3745, "Blue Ring", "Chakra", "Recover 10% Chakra after every action, Secret Skill Damage +10%", "Recover 20% Chakra after every action, Skill Damage +50%", "Deidara"],
[3755, "Shizune's Poison Needle", "Skill", "Weapon Skill Damage +30%", "ATK and Skill Damage +70%", "Shizune"],
[3765, "Tonton's Pearl", "Stats", "Maximum HP and SPD +30%", "Maximum HP, SPD and Skill Damage +50%", "Shizune"],
[3775, "Minato's Forehead Protector", "Chakra", "Chakra Cost -10%", "Chakra Cost -30%, Skill Damage +40%", "Minato Namikaze"],
[3785, "Shisui's Shortsword", "Stats", "ATK and SPD +50%", "ATK and SPD +80%, Cast Speed +1", "Shisui Uchiha"],
[3795, "Puppet (Red Secret)", "Additional", "ATK +40%", "ATK +50%, Skill Hit +3", "Sasori"],
[3805, "Itachi's Forehead Protector", "Chakra", "Chakra Cost -10%, Skill Damage +10%", "Chakra Cost -30%, Skill Damage +50%", "Itachi Uchiha (except ANBU Itachi"],
[3815, "Rubber Training Ball", "Stats", "ATK and SPD +20%, Wind Skill Damage +30%", "ATK +100%, SPD and Skill Damage +50%", "Naruto Uzumaki (Pre-Shippuden)"],
[3825, "Kakashi's Mantle", "Resistance", "Reduce incoming Lightning Skill Damage , Maximum HP +20%", "Reduce incoming Lightning Skill Damage by half, Maximum HP and SPD +40%", "Kakashi Hatake (Shippuden)"],
[3835, "Sai's Picture Book", "Stats", "Maximum HP and SPD +20%", "Maximum HP and SPD +80%, Skill Damage +40%", "Sai"],
[3845, "Celebratory Customized Kunai", "Additional", "SPD +10%", "SPD +30%, Skill Hit +2", "Minato"],
[3855, "Thundercloud", "Additional", "Lightning Skill Damage +30%, Reduce HP by 20% after every action", "For 3 turns, SPD and Lightning Skill Damage +40%, after 3 turns, SPD and Lightning Skill Damage +100%", "Sasuke Uchiha (Shippuden)"],
[3865, "Sasuke's Sleeveless Shirt", "Stats", "Maximum HP +40%", "Maximum HP, ATK and SPD +70%, Recover 10% HP after every action", "Sasuke Uchiha (Shippuden)"],
[3875, "Mifune's Sword", "Stats", "ATK +70%", "ATK +100%. ATK +20% after every action (Max 100%)", "Mifune"],
[3885, "Mifune's Armor", "Resistance", "Reduce the chance of being inflicted by poison and debuff", "Half the effect of poison and debuff, SPD and Skill Damage +40%", "Mifune"],
[3895, "Itachi's Shortsword", "Skill", "Sharingan Skill Damage +30%", "Maximum HP +40%, Skill Damage +100%", "ANBU Itachi Uchiha"],
[3905, "Yugao's Shortsword", "Skill", "Weapon Skill Damage +30%", "Maximum HP +40%, Skill Damage +100%", "Yugao Uzuki"],
[3915, "Shisui's Kunai", "Skill", "Fire Skill Damage +30%", "Skill Damage +50%, Skill Hit +5", "Shisui Uchiha"],
[3925, "ANBU Vest", "Additional", "Recover 7% HP after every action", "Skill Damage +30%, Recover 10% HP after every action", "All ANBU Characters"],
[3935, "Sakura's Pouch", "Skill", "ATK and Taijutsu Skill Damage +20%", "For 3 turns, ATK and Taijutsu Skill Damage +30%; after 3 turns ATK and Taijutsu Skill Damage +100%", "Sakura Haruno (Shippuden)"],
[3945, "Sakura's Forehead Protector", "Chakra", "CHakra Cost -5%, ATK +20%", "Chakra Cost -25%, ATK and Skill Damage +40%", "Sakura Haruno (Shippuden)"],
[3955, "Skipping Stone (Madara)", "Additional", "SPD and Skill Damage +10%", "SPD and Skill Damage +30%, reduce the change of being inflicted by debuff and negative effect by half", "Madara Uchiha"],
[3965, "Madara's Armor", "Stats", "Maximum HP +40%", "Maximum HP and ATK +80%, Chance to recover all Chakra after every action", "Madara Uchiha"],
[3975, "Stone Skipping (Hashirama)", "Additional", "Maximum HP and Skill Damage +10%", "Maximum HP and Skill Damage +30%, reduce the change of being inflicted by debuff and negative effect by half", "Hashirama Senju"],
[3985, "Snowman", "Additional", "Maximum HP and Water Skill Damage +50%, recover 10% HP when attacked", "None", "None"],
[3995, "Pressed Flower", "Skill", "ATK and Byakugan Skill Damage +20%", "For 3 turns, ATK and Byakugan Skill Damage +40%; after 3 turns, ATK and Byakugan Skill Damage +100%", "Hinata Hyuga (Shippuden)"],
[4005, "Hinata's Forehead Protector", "Chakra", "Chakra Cost -5%, ATK +20%", "Chakra Cost -25%, ATK and Skill Damage +40%", "Hinata Hyuga (Shippuden)"],
[4015, "Six Paths Scaffold", "Additional", "For 4 turns, immune to \"Lava Zone\" effect", "None", "None"],
[4035, "Mei's Hair Band", "Stats", "Maximum HP and ATK +40%", "Maximum HP and ATK +70%, Cast Speed +1", "Mei Terumi"],
[1375, "Haku's Mask", "Stats", "ATK and SPD +50%, Maximum HP -20%", "Maximum HP, ATK and SPD +100%", "Haku"],
[4055, "Zabuza's Forehead Protector", "Chakra", "Chakra Cost -10%, ATK +20%", "Chakra Cost -30%, ATK and Skill Damage +20%", "Zabuza Momochi"],
[4065, "Iron Ball", "Skill", "Weapon Skill Damage +30%, SPD +10%", "Weapon Skill Damage +100%', SPD +30%", "Tenten"],
[4075, "Orochimaru's White Snakes", "Additional", "Recover 10% HP after every action", "Recover 10% HP and Chakra after every action, Unique and Summoning Skill Damage +60%", "Orochimaru"],
[4085, "Tayuya's Hat", "Stats", "Maximum HP and ATK +40%", "Maximum HP and ATK +100%, Skill Damage +20%", "Tayuya"],
[4325, "Neji's Pouch", "Skill", "Byakugan Skill Damage +30%, SPD +20%", "Skill Damage +70% and SPD +40%, recover 10% Chakra after every action", "Neji Hyuga"],
[4105, "New Year Card (2017)", "Stats", "Maximum HP and ATK +70%, SPD +30% and recover 10% Chakra after every action", "None", "None"],
[4115, "Rice Cake (2017)", "Stats", "ATK and DEF +70%, SPD +30% and recover 10% HP after every action", "None", "None"],
[4125, "Obito's Eye", "Resistance", "Reduce effect of negative effects", "Immune to negative effects, Skill Damage +20%", "Kakashi Hatake and Obito Uchiha"],
[1205, "Makeout Paradise", "Additional", "Very low chance to dodge skill", "Low Chance to dodge skills, Cast Speed +1", "Kakashi Hatake"],
[4145, "Gai's Forehead Protector", "Chakra", "Chakra Cost -10%", "Chakra Cost -15%, ATK and Skill Damage +30%", "Might Gai"],
[4155, "Ningame Netsuke", "Additional", "Reduce incoming Sharingan and Rinnegan Skill Damage", "Incoming Sharingan and Rinnegan Skill Damage are halved, Taijutsu Skill Damage +100%", "Might Gai"],
[4165, "Hisashi's Kunai", "Skill", "Byakugan Skill Damage +30%", "Byakugan Skill Damage +80%, ATK, DEF and SPD +20%", "Hiashi Hyuga"],
[4175, "Hiashi's Coat", "Stats", "Maximum HP and ATK +40%", "Maximum HP and ATK +80%, Skill Damage +20%", "Hiashi Hyuga"],
[4185, "Eight Trigrams Area", "Additional", "Dodge Rate +30%, Crit Damage +100%", "Dodge Rate +100%, Crit Damage +1000%, Byakugan Skill Damage +50%", "All Hyuga Family Members"],
[4195, "Hinata's Family Crest", "Additional", "Recover 10% Chakra after every action", "Maximum HP +100%, ATK, DEF and SPD +70%", "Hinata Hyuga"],
[8015, "Pain's Black Rod", "Additional", "Maximum Chakra +10", "Maximum Chakra +60 and ATK +100%", "Pain"],
[8025, "Pain's Forehead Protector", "Chakra", "Chakra Cost -10%", "Chakra Cost -50%, SPD and Skill Damage +50%", "Pain"], 
[8035, "Crushed Necklace", "Chakra", "Chakra Cost -10%", "Chakra Cost -50%, ATK and Skill Damage +50%", "Six Tail Form Naruto Uzumaki"],
[8045, "Materialized Bones", "Additional", "Maximum HP and ATK +20%", "Maximum HP, ATK and Tailed Beast Skill Damage +100%", "Six Tail Form Naruto Uzumaki"], 
[8075, "Tailed Beast Right Half", "Additional", "ATK and SPD +20%, Tailed Beast Skill Damage +30%", "ATK +100%, SPD and Skill Damage +50%", "Half Bijuu Gaara"],
[8085, "Gaara's Clothes", "Stats", "Maximum HP, ATK and DEF +30%", "Maximum HP, ATK and DEF +100%", "Gaara (Pre-Shippuden)"],
// [8104, "Red Cloud", "Chakra", "Recover 10% Chakra after every action, ATK +50%, Status Effects and Genjutsu Reduced", "None", "None"],
// [8105, "OP Red Cloud", "Chakra", "Recover 20% Chakra after every action, ATK +100%, Status Effects and Genjutsu Halved", "None  ", "All Akatsuki"],
// [8124, "Orange Cloud", "Chakra", "Chakra Cost Reduced by 10%, Recover 10% chakra after every action, SPD +30%", "None", "None"],
// [8125,]
// [8175,]
// [8185,]
// [8195,]
// [8225,]
// [8235,]
// [8245,]
// [8255,]
// [8275,]
// [8285,]
// [8295,]
// [8305,]
// [8315,]
// [8325,]
// [8335,]
// [8345,]
// [8355,]
// [8365,]
// [8375,]
// [8384,]
// [8385,]
// [8395,]
// [8405,]
// [8415,]
// [8425,]
// [8435,]
// [8445,]
// [8455,]
// [8465,]
// [8475,]
// [8515,]
// [8525,]
// [8535,]
// [8545,]
// [8555,]
// [8565,]
// [8575,]




]












